### ISSUE TITLE
关于KL散度的疑问

### ISSUE THREAD

**Issue by fang-kun** [lancorrect/DAGCN#1]
您的文章中描述使用KL散度是为了“确保 AoGCN 和 SaGCN 学习到的特征是不同的”，但是KL散度作为损失函数，最终不是会寻求两个分布的相似性吗？
关于这点我有很大的疑问，请您指教。

**Comment by lancorrect** [comment]
Hi,

As for your question, KL divergence indeed measures whether both of AoGCN and SaGCN have similar distribution. The more similar they are, the smaller value of KL divergence is. However, this value is negative number and we multiply it by a scalar called $\gamma$, which is also negetive. Hence, the corresponding KL divergence loss is large when they are similar,  and forces different GCNs to learn distinct information.

Hope my explanation could help you.
