### ISSUE TITLE
复现结果不一致的问题

### ISSUE THREAD

**Issue by Allan-waker** [lancorrect/DAGCN#2]
非常感谢您的开源代码，我用您的代码进行复现时，发现和论文的结果不一致，请问是什么问题？需要调整哪些参数？
![image](https://github.com/lancorrect/DAGCN/assets/64625837/3caf2c43-3437-48d8-b99b-ebba25cba773)

![屏幕截图 2024-07-05 210406](https://github.com/lancorrect/DAGCN/assets/64625837/40426444-207d-427a-b086-47889b664fe7)

**Comment by lancorrect** [comment]
Hi,

Different results may be attributed to two reasons. One is that different versions of pakages like pytorch could influence the result. The other is that different types of gpu may affect floats calculation.

Therefore, please check out `requirements.txt` to make sure the versions of your pakages are the same as mine. Also, my suggesion for reproducing our work is to tune three hyperparameters $\alpha$, $\beta$, $\gamma$ for suiting your gpu.

Hope my suggestion could help you :)
